---
name: release
on:
  push:
    tags:
      - '*'
jobs:
  gorelease:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: cd web/app && npm install && npm run build
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
